### ISSUE TITLE
Can't fetch secrets from git in Makefile

### ISSUE THREAD

**Issue by hotogwc** [kickstarter/ios-oss#22] opened 2016-12-19 09:40 UTC
`https://github.com/kickstarter/native-secrets.git` is not existed. So how can I fulfill `Secrets.swift` to get the app really run?

**Comment by jbowlen** [comment] 2016-12-19 16:25
I am having the same issue

**Comment by hotogwc** [comment] 2016-12-20 01:54
I realized the secrets repo should be a private one. How can I get some mock data to run it? In addition, many thanks to open source the great app. I learnt so much from it.

**Comment by nerohoop** [comment] 2016-12-20 10:15
same issue here

**Comment by anurakphoolsawat** [comment] 2016-12-21 04:30
same issue here

**Comment by stephencelis** [comment] 2016-12-21 19:25
Sorry about the confusion! You should be able to ignore that failure and still build after running `make bootstrap`.

**Comment by nerohoop** [comment] 2016-12-22 01:25
there are couple of issues related to swift syntax in Xcode 8, do we have to use Xcode 7?

**Comment by hotogwc** [comment] 2016-12-22 04:16
@stephencelis Thanks for the reply. Yes, I can build successfully but there's no data I can fetch because `Secrets.swift` are just copied from `Secrets.swift.example`. I'm not sure if you did this on purpose for security reason. If so, it's OK with me.

**Comment by stephencelis** [comment] 2016-12-22 19:22
@nerohoop Xcode 7 is required for now. We have several active branches across our projects that are upgrading things to Swift 3, though, so when they get merged in you should be able to run things in Xcode 8 just fine!

@hotogwc This is by design. The OSS client runs against a mock API server. We're looking to enrich this experience in the future but the app should function, just not against our live data.

**Comment by mbrandonw** [comment] 2017-01-11 06:38
we just merged swift 3 support https://github.com/kickstarter/ios-oss/pull/26 and so now xcode 8.2 can be used.

closing this for now, let us know if you have any questions.

**Closed by mbrandonw** 2017-01-11 06:38 UTC
